
name: build-artifacts

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]

    steps:
      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Deps
        run: |
          npm install
          npm postinstall
      - name: Publish
        run: |
          npm make
      - name: Cleanup artifacts
        run: |
          npx rimraf "out/make/!(*.zip|*.exe|*.deb|*.AppImage|*.dmg)"
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os }}
          path: dist
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "out/make/**"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
